export type CourseDifficulty = "beginner" | "intermediate" | "advanced";

export interface CourseData {
  id: string;
  title: string;
  slug: string;
  description: string;
  instructorId: string;
  category: string;
  difficulty: CourseDifficulty;
  duration: number;
  topics: string[];
  progress?: number;
  students?: number;
}

export const COURSE_CATEGORIES = [
  "All",
  "Programming",
  "Web Development",
  "Data Science",
  "AI & ML",
  "DevOps",
  "Design",
] as const;

export const COURSES: CourseData[] = [
  // Programming
  {
    id: "1",
    title: "Data Structures & Algorithms",
    slug: "dsa",
    description: "Master arrays, linked lists, trees, and graphs with hands-on practice.",
    instructorId: "1",
    category: "Programming",
    difficulty: "beginner",
    duration: 480,
    topics: ["Arrays", "Linked Lists", "Trees"],
    progress: 45,
    students: 12500,
  },
  {
    id: "2",
    title: "JavaScript Fundamentals",
    slug: "js-fundamentals",
    description: "From basics to advanced concepts including async and modules.",
    instructorId: "1",
    category: "Web Development",
    difficulty: "beginner",
    duration: 360,
    topics: ["Variables", "Functions", "Async"],
    progress: 80,
    students: 8900,
  },
  {
    id: "3",
    title: "React & Next.js",
    slug: "react-next",
    description: "Build modern web applications with React and Next.js.",
    instructorId: "1",
    category: "Web Development",
    difficulty: "intermediate",
    duration: 420,
    topics: ["Components", "Hooks", "SSR"],
    progress: 0,
    students: 6700,
  },
  {
    id: "4",
    title: "Python for Beginners",
    slug: "python-beginners",
    description: "Learn Python from scratch with practical projects and exercises.",
    instructorId: "1",
    category: "Programming",
    difficulty: "beginner",
    duration: 540,
    topics: ["Syntax", "OOP", "File I/O"],
    students: 15200,
  },
  {
    id: "5",
    title: "Advanced Python",
    slug: "python-advanced",
    description: "Decorators, generators, async programming, and design patterns.",
    instructorId: "1",
    category: "Programming",
    difficulty: "intermediate",
    duration: 480,
    topics: ["Decorators", "Generators", "Async"],
    students: 4200,
  },
  {
    id: "6",
    title: "Java & Spring Boot",
    slug: "java-spring",
    description: "Enterprise Java development with Spring Boot and REST APIs.",
    instructorId: "1",
    category: "Programming",
    difficulty: "intermediate",
    duration: 600,
    topics: ["Spring", "REST", "Security"],
    students: 5800,
  },
  {
    id: "7",
    title: "C++ Fundamentals",
    slug: "cpp-fundamentals",
    description: "Memory management, pointers, and object-oriented C++.",
    instructorId: "1",
    category: "Programming",
    difficulty: "intermediate",
    duration: 480,
    topics: ["Pointers", "OOP", "STL"],
    students: 3100,
  },
  {
    id: "8",
    title: "Go (Golang) Programming",
    slug: "go-programming",
    description: "Concurrent programming and building scalable services with Go.",
    instructorId: "1",
    category: "Programming",
    difficulty: "intermediate",
    duration: 360,
    topics: ["Goroutines", "Channels", "APIs"],
    students: 2900,
  },
  // Web Development
  {
    id: "9",
    title: "HTML, CSS & Responsive Design",
    slug: "html-css",
    description: "Build beautiful, responsive websites from scratch.",
    instructorId: "1",
    category: "Web Development",
    difficulty: "beginner",
    duration: 300,
    topics: ["HTML5", "CSS3", "Flexbox"],
    students: 18200,
  },
  {
    id: "10",
    title: "Node.js & Express",
    slug: "node-express",
    description: "Backend development with Node.js, Express, and MongoDB.",
    instructorId: "1",
    category: "Web Development",
    difficulty: "intermediate",
    duration: 420,
    topics: ["REST APIs", "Auth", "Database"],
    students: 7200,
  },
  {
    id: "11",
    title: "TypeScript Mastery",
    slug: "typescript",
    description: "Type-safe JavaScript for scalable applications.",
    instructorId: "1",
    category: "Web Development",
    difficulty: "intermediate",
    duration: 360,
    topics: ["Types", "Generics", "Decorators"],
    students: 5400,
  },
  {
    id: "12",
    title: "Vue.js 3 Complete Guide",
    slug: "vuejs",
    description: "Reactive UIs with Vue 3 Composition API and Pinia.",
    instructorId: "1",
    category: "Web Development",
    difficulty: "intermediate",
    duration: 480,
    topics: ["Composition API", "Pinia", "Router"],
    students: 4100,
  },
  // Data Science
  {
    id: "13",
    title: "Data Science with Python",
    slug: "data-science-python",
    description: "Pandas, NumPy, Matplotlib for data analysis and visualization.",
    instructorId: "1",
    category: "Data Science",
    difficulty: "intermediate",
    duration: 540,
    topics: ["Pandas", "NumPy", "Visualization"],
    students: 9500,
  },
  {
    id: "14",
    title: "SQL for Data Analysis",
    slug: "sql-data",
    description: "Write efficient queries with joins, subqueries, and window functions.",
    instructorId: "1",
    category: "Data Science",
    difficulty: "beginner",
    duration: 240,
    topics: ["SELECT", "JOINs", "Window Functions"],
    students: 11200,
  },
  {
    id: "15",
    title: "Statistics for Data Science",
    slug: "statistics",
    description: "Probability, distributions, hypothesis testing, and regression.",
    instructorId: "1",
    category: "Data Science",
    difficulty: "intermediate",
    duration: 480,
    topics: ["Probability", "Regression", "Testing"],
    students: 6200,
  },
  {
    id: "16",
    title: "Data Visualization",
    slug: "data-viz",
    description: "Create compelling charts with D3.js, Plotly, and Tableau.",
    instructorId: "1",
    category: "Data Science",
    difficulty: "intermediate",
    duration: 360,
    topics: ["D3.js", "Plotly", "Dashboard"],
    students: 3800,
  },
  // AI & ML
  {
    id: "17",
    title: "Machine Learning Fundamentals",
    slug: "ml-fundamentals",
    description: "Supervised learning, regression, classification, and evaluation.",
    instructorId: "1",
    category: "AI & ML",
    difficulty: "intermediate",
    duration: 600,
    topics: ["Regression", "Classification", "Scikit-learn"],
    students: 8400,
  },
  {
    id: "18",
    title: "Deep Learning with PyTorch",
    slug: "pytorch",
    description: "Neural networks, CNNs, and RNNs with PyTorch.",
    instructorId: "1",
    category: "AI & ML",
    difficulty: "advanced",
    duration: 720,
    topics: ["Neural Nets", "CNN", "RNN"],
    students: 5100,
  },
  {
    id: "19",
    title: "LLMs & Prompt Engineering",
    slug: "llm-prompting",
    description: "Work with ChatGPT, Claude, and build LLM applications.",
    instructorId: "1",
    category: "AI & ML",
    difficulty: "intermediate",
    duration: 300,
    topics: ["Prompts", "RAG", "Fine-tuning"],
    students: 12800,
  },
  {
    id: "20",
    title: "Computer Vision Basics",
    slug: "computer-vision",
    description: "Image classification, object detection, and segmentation.",
    instructorId: "1",
    category: "AI & ML",
    difficulty: "intermediate",
    duration: 480,
    topics: ["CNN", "ResNet", "YOLO"],
    students: 3600,
  },
  // DevOps
  {
    id: "21",
    title: "Docker & Kubernetes",
    slug: "docker-k8s",
    description: "Containerize apps and deploy with Kubernetes.",
    instructorId: "1",
    category: "DevOps",
    difficulty: "intermediate",
    duration: 480,
    topics: ["Docker", "K8s", "Helm"],
    students: 6200,
  },
  {
    id: "22",
    title: "CI/CD with GitHub Actions",
    slug: "cicd",
    description: "Automate pipelines with GitHub Actions and Jenkins.",
    instructorId: "1",
    category: "DevOps",
    difficulty: "intermediate",
    duration: 240,
    topics: ["GitHub Actions", "Jenkins", "Testing"],
    students: 4500,
  },
  {
    id: "23",
    title: "AWS Cloud Practitioner",
    slug: "aws",
    description: "EC2, S3, Lambda, and core AWS services.",
    instructorId: "1",
    category: "DevOps",
    difficulty: "beginner",
    duration: 420,
    topics: ["EC2", "S3", "Lambda"],
    students: 7800,
  },
  {
    id: "24",
    title: "Linux & Shell Scripting",
    slug: "linux-shell",
    description: "Command line, bash scripting, and system administration.",
    instructorId: "1",
    category: "DevOps",
    difficulty: "beginner",
    duration: 360,
    topics: ["Bash", "Cron", "Permissions"],
    students: 9200,
  },
  // Design
  {
    id: "25",
    title: "UI/UX Design",
    slug: "ui-ux",
    description: "User research, wireframes, prototypes, and design systems.",
    instructorId: "1",
    category: "Design",
    difficulty: "beginner",
    duration: 480,
    topics: ["Figma", "Wireframes", "Prototyping"],
    students: 6700,
  },
  {
    id: "26",
    title: "Figma for Developers",
    slug: "figma",
    description: "Design handoff and collaboration for dev teams.",
    instructorId: "1",
    category: "Design",
    difficulty: "beginner",
    duration: 180,
    topics: ["Figma", "Components", "Tokens"],
    students: 4100,
  },
  {
    id: "27",
    title: "Design Systems",
    slug: "design-systems",
    description: "Build scalable component libraries and design tokens.",
    instructorId: "1",
    category: "Design",
    difficulty: "intermediate",
    duration: 360,
    topics: ["Tokens", "Components", "Documentation"],
    students: 2800,
  },
];
